#!/bin/bash
# Script that lists all databases in MongoDB
mongo --eval "db.adminCommand('listDatabases').databases.forEach(function(d) { print(d.name + '\t' + (d.sizeOnDisk/1024/1024/1024).toFixed(3) + 'GB') })" --quiet
